FizzBuzz課題の提出
yyy-Szk/ruby-practices pull request #1
Opened 2021-08-29 13:12 UTC by yyy-Szk

rubocop実行時に「caseではなくif(およびelsif)を使え」と怒られましたが、

この時点で修正すべきなのか、また「なぜそちらの方がいいのか？」がわからなかったため修正しておりません。

もし修正すべきであれば、ご指摘のほどよろしくお願いいたします。

2021-08-29 13:13 UTC, yyy-Szk commented
## 要件

```
1から20までの数をプリントするプログラムを書け。

ただし3の倍数のときは数の代わりに｢Fizz｣と、5の倍数のときは｢Buzz｣とプリントし、3と5両方の倍数の場合には｢FizzBuzz｣とプリントすること。
```

2021-09-02 07:08 UTC, komagata requested changes

2021-09-02 07:08 UTC, komagata commented on 01.fizzbuzz/fizz_buzz.rb
> +
不要な改行が残っているようです〜

2021-09-04 11:02 UTC, yyy-Szk commented on 01.fizzbuzz/fizz_buzz.rb
> +
ご指摘ありがとうございます。

修正いたします！

2021-09-04 11:05 UTC, yyy-Szk commented on 01.fizzbuzz/fizz_buzz.rb
> +
以下にて修正いたしました！

https://github.com/yyy-Szk/ruby-practices/pull/1/commits/89a4a67b068b19ba46ad4fbd78f16cd2b4f8437c

2021-09-06 06:36 UTC, komagata commented
> https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/CaseLikeIf

Rubocopのそれぞれのルールについて載っているので調べてみてください〜

2021-09-06 10:41 UTC, yyy-Szk commented
@komagata 

rubocopのルールについて調査してみました。

自分が該当していたものは以下の2つでした

- [EmptyCaseCondition](https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/EmptyCaseCondition)
- [FrozenStringLiteralComment](https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/FrozenStringLiteralComment)

前者については記述した方が良さそうなので追記いたします

後者についても、基本的には（少なくとも`rubocop-fjord`では）`空のcase`を使用せず、`if-elsif-else`を使用した方がわかりやすいと考えている、ということのようなので修正させていただきます！

2021-09-06 10:43 UTC, yyy-Szk commented
`StringLiterals`もですね、、、

シングルクォートを使用する形で修正いたします

2021-09-06 10:48 UTC, yyy-Szk commented
@komagata 

それぞれ以下のコミットにて修正いたしました！

- https://github.com/yyy-Szk/ruby-practices/pull/1/commits/5a3f265b8e1fe89d4de92e8e7fbc0799bcf03e21
- https://github.com/yyy-Szk/ruby-practices/pull/1/commits/91cce4686115e57087ac33cd3ee389a5e683b811
- https://github.com/yyy-Szk/ruby-practices/pull/1/commits/7c0ca803fc771963d174a09b3224385111a18031

2021-09-07 14:20 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2026-01-13 00:44 UTC, closed without merging